---
title: "ProjectBroadAnnots.Rmd"
author: "Jenna LaBelle"
date: "10/07/22"
output: html_document
---

## Expression patterns of various genes of interest acros PD1 treated samples/untreated GBM

```{r}
library(Seurat) 
library(ggplot2)
library(ggpubr)

base_dir = "/Users/jlabelle/"
script_dir = "Dropbox (Partners HealthCare)/FilbinLab/data_analysis/Scripts/"
working_dir<- paste0(base_dir, 
                     "Dropbox (Partners HealthCare)/FilbinLab/",
                     "data_analysis/Projects/git_repos/Pedi_Immune/PD1_Treat/comparisonToUntreated/")

analysis_dir<- paste0(working_dir, "/analysis/clonal_analysis/")
figure_dir<- paste0(working_dir, "/figures/clonal_analysis/")
data_dir<- paste0(working_dir, "analysis/")

if(!dir.exists(figure_dir)){dir.create(figure_dir, recursive = TRUE)}
if(!dir.exists(analysis_dir)){dir.create(analysis_dir, recursive = TRUE)}

preprocessing = paste0(base_dir, script_dir, "single_cell_preprocessing_helper_functions.R")
nmf_helper = paste0(base_dir, script_dir, "NMF_helper_function.R")
source(preprocessing)
source(nmf_helper)
source("../HelperFunctions.R")

```


## Load seurat objects, colors, tcr info

```{r}
## Set whether to use integrated or unintegrated objects
integration<- "Harmony" ## NoInt or Harmony- as of 11/1/22, not using seurat integration (SeuratInt) downstream
figure_dir_use<- paste0(figure_dir, integration, "/")
if(!dir.exists(figure_dir_use)){dir.create(figure_dir_use)}

full_cohort_dir<- "../../ImmuneCellAnalysis/"


## Load list of merged ss2/10x seurat objects (6 total- cd4/cd8/myeloid for tenx and ss2)
ss2_seurat<- readRDS("analysis/project_programs/ss2_seurat_list_cd4.cd8.myeloid.Rds")
tenx_seurat<- readRDS("analysis/project_programs/tenx_seurat_list_cd4.cd8.myeloid.Rds")

  ## Subset to just t cells
  ss2_seurat<- ss2_seurat[c("ss_cd4", "ss_cd8")]
  tenx_seurat<- tenx_seurat[c("tenx_cd4", "tenx_cd8")]
  
  ## CD4 cell names have "_1" appended- fix
  tenx_seurat$tenx_cd4<- RenameCells(tenx_seurat$tenx_cd4, new.names= gsub("_1", "", colnames(tenx_seurat$tenx_cd4)))
  tenx_seurat$tenx_cd4<- RenameCells(tenx_seurat$tenx_cd4, new.names= gsub("_2", "", colnames(tenx_seurat$tenx_cd4)))

## Colors 
tcell_colors<- readRDS(paste0(full_cohort_dir, "/plot_colors/Tcell.programs_rank8sharedByunion_reAnnot.Rds"))
myeloid_colors<- readRDS(paste0(full_cohort_dir, "/plot_colors/Myeloid_program_colors.Rds"))
myeloid_colors<- myeloid_colors$rank6
immune_colors<- c(tcell_colors, myeloid_colors)
colors_treatment<- c(PD1="orange", Untreated="purple")

  
## TCR data- load for PD1, BT1857, BT1478, 10X (treated and untreated)
  ## SmartSeq2
  ## BT1857 and BT1478 data load separately bc the latter processed by Orr, former by me/Li
    ## PD1- raw cell_data.csv from tracer available
    pd1_tcr_dir<- "../SS2/Immune/data/tracer_output/"
    pd1_tcr_samples<- list.files(pd1_tcr_dir)
    all_tcr<- lapply(pd1_tcr_samples, function(sample){
      tmp<- read.csv(paste0(pd1_tcr_dir, sample, "/cell_data.csv"))
      tmp$sample<- sample
      return(tmp)
    })
    pd1_tcr<- do.call(rbind, all_tcr)
    
    ## BT1478 (whole cohort, subset to just this sample)
    fullCohort_tcr_dir<-"../../ImmuneCellAnalysis/data/data_fromOrr"
    load(paste0(working_dir, fullCohort_tcr_dir, "2020_12_10_clonalTcells_cluster.Rda"))
    bt1478_cells_with_tcr<- tcell.reconstructed$BT1478
    bt1478_clonotypes<- clonotypes.all[clonotypes.all$experiment=="BT1478",]
    rm(clonal); rm(clonotypes.all); rm(gcdata); rm(clonotypes.cells)
    
    ## BT1857- raw cell_data.csv from tracer available
    newSamples_tcr_dir<- "../../ImmuneCellAnalysis/01_Preprocessing/01_Tracer_Preprocess/data/BT1857/output/filtered_TCRAB_summary/"
    bt1857_tcr<- read.csv(paste0(newSamples_tcr_dir, "cell_data.csv"))
    bt1857_tcr$sample<- "BT1857"
    
   ## Add BT1857/pd1 TCR info together + subset to "productive" TCRs (either A or B is not "")
    pd1_bt1857_tcr<- rbind(pd1_tcr, bt1857_tcr)
    rownames(pd1_bt1857_tcr)<- pd1_bt1857_tcr$cell_name
    pd1_bt1857_tcr<-pd1_bt1857_tcr[pd1_bt1857_tcr$A_productive != "" | pd1_bt1857_tcr$B_productive != "",]
    pd1_bt1857_tcr<- pd1_bt1857_tcr[,c("clonal_group", "group_size")]
    rownames(pd1_bt1857_tcr)<- gsub( "_", "\\.",rownames(pd1_bt1857_tcr))
  
  ## tenX
  pd1_tenx_tcr<- read.csv("../tenX/data/multi/per_sample_outs/BT2062/vdj_t/filtered_contig_annotations.csv")
  bt1857_tenx_tcr<- read.csv("../../ImmuneCellAnalysis/tenX/unTreatedAlone/data/VDJ/multi/per_sample_outs/BT1857/vdj_t/filtered_contig_annotations.csv")
  pd1_tenx_tcr$raw_clonotype_id_sample<- paste0("BT2062_", pd1_tenx_tcr$raw_clonotype_id)
  bt1857_tenx_tcr$raw_clonotype_id_sample<- paste0("BT1857_", bt1857_tenx_tcr$raw_clonotype_id)
  tenx_tcr<- rbind(pd1_tenx_tcr, bt1857_tenx_tcr)
```

## For each cell: add 1) whether TCR was reconstructed 2) clonal group
```{r}
## SS2
ss2_seurat<- lapply(ss2_seurat, function(seurat){
  
  ## Add info for BT1478 separately- different structure to results
  bt1478_seurat<- subset(seurat, sample=="BT1478")
  bt1478_seurat$tcr_reconstructed<- ifelse(colnames(bt1478_seurat) %in% bt1478_cells_with_tcr, "Yes", "No")
  bt1478_seurat<- AddMetaData(bt1478_seurat, bt1478_clonotypes[,!colnames(bt1478_clonotypes) %in% c("cell_name", "experiment")])
  
  ## Add info for pd1/BT1478
  remaining_seurat<- subset(seurat, sample!="BT1478")
  remaining_seurat$tcr_reconstructed<- ifelse(colnames(remaining_seurat) %in% rownames(pd1_bt1857_tcr),"Yes", "No")
  remaining_seurat<- AddMetaData(remaining_seurat, pd1_bt1857_tcr)
  
  ## Merge new meta
  new_meta<- rbind(bt1478_seurat@meta.data[,c("tcr_reconstructed", "clonal_group", "group_size")],
                   remaining_seurat@meta.data[,c("tcr_reconstructed", "clonal_group", "group_size")])
  seurat<- AddMetaData(seurat, new_meta)
  
  
  ## Assign as "clonal" (clonal size > 1; or isn't NA) or nonclonal
  seurat$clonal_updated<- ifelse(!is.na(seurat$group_size), "clonal", "nonclonal")
  return(seurat)
})


## tenX
c_size<- as.data.frame(table(tenx_tcr$raw_clonotype_id_sample))
tenx_seurat<- lapply(tenx_seurat, function(seurat){
  seurat$clonal_group<- as.character(plyr::mapvalues(colnames(seurat), tenx_tcr$barcode, tenx_tcr$raw_clonotype_id_sample, warn_missing = FALSE))
  seurat$v_gene<- as.character(plyr::mapvalues(colnames(seurat), tenx_tcr$barcode, tenx_tcr$v_gene, warn_missing = FALSE))
  seurat$j_gene<- as.character(plyr::mapvalues(colnames(seurat), tenx_tcr$barcode, tenx_tcr$j_gene, warn_missing = FALSE))
  
  seurat$group_size<- as.numeric(as.character(plyr::mapvalues(seurat$clonal_group, c_size$Var1, c_size$Freq, warn_missing = FALSE)))
  seurat$clonal<- ifelse(seurat$group_size>1, "clonal",ifelse(is.na(seurat$group_size), NA, "nonclonal"))
  seurat$group_size_max20<- ifelse(seurat$group_size>20, 20, seurat$group_size)
  
  seurat$tcr_reconstructed<- ifelse(!is.na(seurat$clonal), "Yes", "No")
  return(seurat)
})
```

## Plot group size of clonotype (including clones where n=1; i.e., TCR reconstructed but not expanded) in a histogram
```{r}
seurat_list<- tenx_seurat

## Plot clonotype sizes (raw)
all_plots<- lapply(seurat_list, function(seurat){
  meta<- seurat@meta.data
  
  ## Subset to cells with TCR
  meta<- meta[meta$tcr_reconstructed=="Yes",]
  
  ## For "group size" = NA: change to 1 (these are cells with a TCR but not expanded. That is, in their own clone of size n=1)
  ## This is only required for ss2
  meta$group_size<- ifelse(is.na(meta$group_size), 1, meta$group_size)
  
  
  ## Plot in hist, by treatment
  ggplot(meta, aes(x=group_size, fill=Treatment))+
    geom_histogram(bins=4)+
    ggtitle(unique(meta$detailed_annot))+
    theme_bw()+
    scale_fill_manual(values=colors_treatment)+
    xlab("Clonotype size")
})
cowplot::plot_grid(plotlist=all_plots)

## Plot clonotype sizes as a proportion of total TCRs
## % of all TCRs with clonotype size 1, etc
all_plots<- lapply(seurat_list, function(seurat){
  meta<- seurat@meta.data
  
  ## Subset to cells with TCR
  meta<- meta[meta$tcr_reconstructed=="Yes",]
  
  ## For "group size" = NA: change to 1 (these are cells with a TCR but not expanded. That is, in their own clone of size n=1)
  meta$group_size<- ifelse(is.na(meta$group_size), 1, meta$group_size)

  ## Get number/proportion of all cells (with TCR) in each clonotype size
  bd<- as.data.frame(table(meta$group_size, meta$Treatment))
  colnames(bd)<- c("ClonotypeSize", "Treatment", "NumberCells")
  bd<- bd %>% group_by(Treatment) %>% mutate(PerCells=NumberCells/sum(NumberCells)) %>% as.data.frame()
  
  ## Plot
  ggplot(bd, aes(x=ClonotypeSize, y=PerCells, fill=Treatment))+
    geom_bar(stat="identity", position="dodge")+
    theme_bw()+
    xlab("Clonotype size")+
    ylab("Percentage of cells in clonotype size")+
    scale_fill_manual(values=colors_treatment)+
    ggtitle(unique(meta$detailed_annot))
})
cowplot::plot_grid(plotlist=all_plots)

## Boxplot of clonotype size by program
all_plots<- lapply(seurat_list, function(seurat){
  meta<- seurat@meta.data
  
  ## Subset to cells with TCR
  meta<- meta[meta$tcr_reconstructed=="Yes",]
  
  ## For "group size" = NA: change to 1 (these are cells with a TCR but not expanded. That is, in their own clone of size n=1)
  meta$group_size<- ifelse(is.na(meta$group_size), 1, meta$group_size)
  
  ## Plot
  ggplot(meta, aes(x=Program_projected, y=group_size, fill=Treatment))+
    geom_boxplot()
    geom_bar(stat="identity", position="dodge")+
    theme_bw()+
    xlab("Clonotype size")+
    ylab("Percentage of cells in clonotype size")+
    scale_fill_manual(values=colors_treatment)+
    ggtitle(unique(meta$detailed_annot))
})
cowplot::plot_grid(plotlist=all_plots)
```

