---
title: "R Notebook"
output: html_document
---

```{r}
base_dir = "/Users/jlabelle/"
working_dir<- paste0(base_dir, "Dropbox (Partners HealthCare)/FilbinLab/data_analysis/Projects/git_repos/Pedi_Immune/TumorCellAnnotation/AllSubtypesTogether/")
script_dir = "Dropbox (Partners HealthCare)/FilbinLab/data_analysis/Scripts/"

fig_folder = paste0("figures/ComparingAllNMF/")
nmf_analysis_folder = paste0("analysis/nmf/Merge/")
nmf_folder = "analysis/nmf/"
liger_analysis_folder<- "analysis/liger/"

preprocessing = paste0(base_dir, script_dir, "single_cell_preprocessing_helper_functions.R")
nmf_helper = paste0(base_dir, script_dir, "NMF_helper_function.R")
source(preprocessing)
source(nmf_helper)

```

## Load in count matrix
```{r}
## Read in cm list, sample list, and tumor/normal annotation
load("../Preprocessing/QC/analysis/cm_list.Robj")
tumor_stat = readRDS("../Preprocessing/inferCNV/analysis/inferCNV/seurat/call_tumor.rds")
samples = readRDS("../Preprocessing/QC/analysis/samples.rds")

## Keep maligant cells
cm<- cm_list$raw_data
cm = cm_list$raw_data[, tumor_stat=="Malignant"]
samples_tumor = samples[tumor_stat=="Malignant"]
length(samples_tumor); sum(colnames(cm)==names(samples_tumor))

```

## read in my NMF programs- already scored
```{r}
## My LIGER NMF programs
liger_score<- readRDS(paste0(liger_analysis_folder, "nmf_score_AllFactors", ".Rds"))
liger_score<- liger_score[,grep("factor", colnames(liger_score))]
colnames(liger_score)<- paste0(c("Progenitor_", "Metabolic_", "", "", "AC_", "", "", "", "G2M_",
                                 "", "ImmuneReactive_", "", "", "", "SPhase_", "", "RibosomeActive_",
                                 ""),
                               colnames(liger_score))
liger_score<- liger_score[,grep("_", colnames(liger_score))]
liger_score<-liger_score[,colnames(liger_score) %in% paste0("factor", c(6,10,14,19,3,4,13,18,8))]
liger_score<-liger_score[order(rownames(liger_score)),]
```

## Read in previous NMF programs, then score
```{r}
## Previous programs
published_dir<- paste0(base_dir, "Dropbox (Partners HealthCare)/FilbinLab/data_analysis/PublishedDatasets/FilbinPublishedDatasets/Metaprograms/")

midline_genesets<-readRDS(paste0(published_dir, "midlinePreviousPrograms_OC.AC.OPC.MES1.rds"))
hemi_genesets<-readRDS(paste0(published_dir, "hemisphericPreviousPrograms_2019_OC.rds"))
epn_genesets<- read.csv(paste0(published_dir,"TableS2_epn2020Paper_Metaprograms_AllMerged.csv"))
epn_genesets<- as.list(epn_genesets)

all_genesets<- c(midline_genesets, hemi_genesets, epn_genesets)

## Score, assign each cell to its highest scoring metaprogram
scores<-lapply(all_genesets,function(x){scoreSignature(cm_center, cm_mean, x)})
scores<-as.data.frame(scores)
colnames(scores)<- paste0(colnames(scores), "_PreviousPrograms")
scores<- scores[order(rownames(scores)),]
colnames(scores)<- gsub("_PreviousPrograms_PreviousPrograms", "", colnames(scores))
```


## Combine all scores, then pearson correlation + HC
```{r}
## Merge scores
sum(rownames(scores) ==rownames(liger_score)); nrow(scores)

all_scores<- cbind(scores, liger_score)

## Cluster using pearson
all_pearson = cor(all_scores, method="pearson")

## Cluster using pearson --> HC
all_hc<-clusterNmfFactors(all_scores)
all_cor<-all_hc$cor_coef[all_hc$hc_obj$order, all_hc$hc_obj$order]

range<-max(abs(all_cor))

hm_colors = rev((brewer.pal(n=9, name="RdBu")))
hm_colors = colorRampPalette(colors = hm_colors)
pheatmap(all_cor, color = hm_colors(100), 
         breaks = seq(-range, range, length.out = 100),
         cluster_rows = F, cluster_cols = F, 
         annotation_names_row = F, annotation_names_col =T,
         show_rownames = T, show_colnames = F,
         filename = paste0(fig_folder, "AllNMFPrograms_Correlation_SemiShared.png"), 
         width = 12, height = 6)

```

