---
title: "R Notebook"
output: html_document
---

```{r}
base_dir = "/Users/jlabelle/"
script_dir = "Dropbox (Partners HealthCare)/FilbinLab/data_analysis/Scripts/"
working_dir<- paste0(base_dir, 
                     "Dropbox (Partners HealthCare)/FilbinLab/",
                     "data_analysis/Projects/git_repos/Pedi_Immune/TumorCellAnnotation/AllSubtypesTogether/")

preprocessing = paste0(base_dir, script_dir, "single_cell_preprocessing_helper_functions.R")
nmf_helper = paste0(base_dir, script_dir, "NMF_helper_function.R")
plot_helper = paste0(base_dir, script_dir, "Plotting_helper_functions.R")
stat_helper = paste0(base_dir, script_dir, "common_stat_test.R")
source(preprocessing)
source(nmf_helper)
source(plot_helper)
source(stat_helper)

figure_dir<- "figures/ComparingAllCellAnnots/"

```

## Load in full filtered count matrix
```{r}
load("analysis/seurat/seurat_obj.Robj")
```

## Load in cell type markers of interest
```{r}
## Midline histone mutant
load("../BySubtype/Midline/Midline_HistoneMutant/analysis/ManualCellAnnot_Markers.Robj")
midlineHistoneMut_markers<-ManualCellAnnot_Markers_filt
midlineHistoneMut_markers<- split(midlineHistoneMut_markers, f=midlineHistoneMut_markers$cluster)
midlineHistoneMut_markers<- lapply(midlineHistoneMut_markers, function(x){x$gene})
names(midlineHistoneMut_markers)<-paste0("MidlineHistoneMut_", names(midlineHistoneMut_markers))

## Hemispheric BCOR
load("../BySubtype/Hemispheric/BCOR/analysis/ManualCellAnnot_Markers.Robj")
hemiBCOR_markers<-ManualCellAnnot_Markers_filt
hemiBCOR_markers<- split(hemiBCOR_markers, f=hemiBCOR_markers$cluster)
hemiBCOR_markers<- lapply(hemiBCOR_markers, function(x){x$gene})
names(hemiBCOR_markers)<-paste0("HemiBCOR_", names(hemiBCOR_markers))

## Hemispheric G34RV
g34rv_programs<- read.csv("../BySubtype/Hemispheric/HistoneMut/analysis/FromIlon_G34RV_Markers_FreshFrozen.csv")
hemiHistoneMutant_markers<-as.list(g34rv_programs)
names(hemiHistoneMutant_markers)<-paste0("HemiHistoneMut_", 
                                         gsub("fresh.", "",names(hemiHistoneMutant_markers)))


## Ependymoma: PF/ST/SP
load("../BySubtype/Ependymoma/analysis/epn_pf_Markers.Robj")
load("../BySubtype/Ependymoma/analysis/epn_st_Markers.Robj")
load("../BySubtype/Ependymoma/analysis/epn_sp_Markers.Robj")

epnPF_markers<-split(pf_Markers_filt, f=pf_Markers_filt$cluster)
epnST_markers<-split(st_Markers_filt, f=st_Markers_filt$cluster)
epnSP_markers<-split(sp_Markers_filt, f=sp_Markers_filt$cluster)

epnPF_markers<- lapply(epnPF_markers, function(x){x$gene})
epnST_markers<- lapply(epnST_markers, function(x){x$gene})
epnSP_markers<- lapply(epnSP_markers, function(x){x$gene})

epnPF_markers<- epnPF_markers[lapply(epnPF_markers, length)>0]

## Add all markers to 1 list
all_markers<- c(hemiBCOR_markers, midlineHistoneMut_markers, hemiHistoneMutant_markers,
                epnPF_markers, epnSP_markers, epnST_markers)
```

## Score each cell for each program
```{r}
cm_center<-NormCenter(seurat_obj@assays$RNA@counts)
cm_center<-cm_center$center_data
cm_mean = log2(rowMeans(seurat_obj@assays$RNA@counts)+1)

## Score, assign each cell to its highest scoring metaprogram
scores<-lapply(all_markers,function(x){scoreSignature(cm_center, cm_mean, x)})
scores<-as.data.frame(scores)
scores<- scores[order(rownames(scores)),]
```

## Pairwise correlation and HC
```{r}
## Cluster using pearson
all_pearson = cor(scores, method="pearson")

## Cluster using pearson --> HC
all_hc<-clusterNmfFactors(scores)
all_cor<-all_hc$cor_coef[all_hc$hc_obj$order, all_hc$hc_obj$order]

range<-max(abs(all_cor))

hm_colors = rev((brewer.pal(n=9, name="RdBu")))
hm_colors = colorRampPalette(colors = hm_colors)
pheatmap(all_cor, color = hm_colors(100), 
         breaks = seq(-range, range, length.out = 100),
         cluster_rows = F, cluster_cols = F, 
         annotation_names_row = F, annotation_names_col =T,
         show_rownames = T, show_colnames = F,
         filename =  paste0(figure_dir, "HemiBCOR_MidlineHistoneMut_HemiHistoneMut_Epn_ManualCellAnnots.png"), 
         width = 6, height = 6)
```

