---
title: "MergeSamples_QC_ToSeurat.Rmd"
author: "Jenna LaBelle"
date: "11/04/21"
output: html_document
---


```{r}
library(Seurat) 

base_dir = "/Users/jlabelle/"
script_dir = "Dropbox (Partners HealthCare)/FilbinLab/data_analysis/Scripts/"
working_dir<- paste0(base_dir, 
                     "Dropbox (Partners HealthCare)/FilbinLab/",
                     "data_analysis/Projects/PD1_Treatment/Immune/")


analysis_dir_tmp<- paste0(working_dir, "/analysis/detailed_annotation/")
figure_dir_tmp<- paste0(working_dir, "/figures/detailed_annotation/")
data_dir_tmp<- paste0(working_dir,"/analysis/broad_annotation/")

if(!dir.exists(figure_dir_tmp)){dir.create(figure_dir_tmp, recursive = TRUE)}
if(!dir.exists(analysis_dir_tmp)){dir.create(analysis_dir_tmp, recursive = TRUE)}

preprocessing = paste0(base_dir, script_dir, "single_cell_preprocessing_helper_functions.R")
nmf_helper = paste0(base_dir, script_dir, "NMF_helper_function.R")
source(preprocessing)
source(nmf_helper)

```

## Read in processed seurat objects
```{r}
integration<- "HarmonyInt/" ## HarmonyInt/ or ""

analysis_dir<- paste0(analysis_dir_tmp, integration, "/")
figure_dir<- paste0(figure_dir_tmp, integration, "/")
for(x in c(analysis_dir, figure_dir)){if(!dir.exists(x)){dir.create(x)}}
data_dir<- paste0(data_dir_tmp, integration, "/")

immune_seurat<- readRDS(paste0(data_dir,"tcell.myeloid_seurat.Rds"))
tcell_seurat<- readRDS(paste0(data_dir,   "tcell_seurat.Rds"))
myeloid_seurat<- readRDS(paste0(data_dir, "myeloid_seurat.Rds"))

```


#############################
## Myeloid cell annotation ##
#############################

For now, just identifying B cells and dendritic cells
May also identify/annotation macrophages and microglia here
```{r}
bcell_markers<- c("BCL6", "CD22", "CD86", "TLR9", "CD19", "CD40", "CD72" ) ## plasma, mature, activated, memory, rest are pan Bcell
dendritic_markers<- c("FLT3", "CD207", "CD1A", "CD1C", "FCER1A",
                      "NOTCH2")

FeaturePlot(myeloid_seurat, features=bcell_markers, ncol = 3)
ggsave(paste0(figure_dir, "Myeloid_BcellMarkers.png"), width=12, height=12)

FeaturePlot(myeloid_seurat, features=dendritic_markers, ncol = 3)
ggsave(paste0(figure_dir, "Myeloid_DendriticMarkers.png"), width=12, height=8)


## annotate clusters based on these markers
cluster_annot<- c(3)
names(cluster_annot)<- c("DC")
myeloid_seurat$detailed_annot<- ifelse(myeloid_seurat$seurat_clusters %in% cluster_annot,
                                            plyr::mapvalues(as.character(myeloid_seurat$seurat_clusters), 
                                                            cluster_annot, names(cluster_annot)),
                                            "Myeloid")
saveRDS(myeloid_seurat, file=paste0(analysis_dir, "myeloid_seurat.Rds"))

## Remove DC/Bcells and rerun seurat
myeloid_seurat_noDC.B<- subset(myeloid_seurat, detailed_annot=="Myeloid")
myeloid_seurat_noDC.B_meta<- myeloid_seurat_noDC.B@meta.data

if(integration=="HarmonyInt/"){
 myeloid_seurat_noDC.B<- RunFullSeurat(myeloid_seurat_noDC.B@assays$RNA@counts,RunHarmony = TRUE,
                                             samples=myeloid_seurat_noDC.B$sampleid) 
}else{
  myeloid_seurat_noDC.B<- RunFullSeurat_Immune(myeloid_seurat_noDC.B@assays$RNA@counts,
                                             myeloid_seurat_noDC.B$sampleid)
}

myeloid_seurat_noDC.B<- AddMetaData(myeloid_seurat_noDC.B, 
                                    myeloid_seurat_noDC.B_meta[,!colnames(myeloid_seurat_noDC.B_meta) %in%
                                                                 colnames(myeloid_seurat_noDC.B@meta.data)])
saveRDS(myeloid_seurat_noDC.B, file=paste0(analysis_dir, "myeloid_seurat_noDC.B.Rds"))

```

############################
## Identify CD4/CD8 cells ##
############################


```{r}
## Decrease resolution
if(integration=="HarmonyInt/"){
  tcell_seurat<- FindClusters(tcell_seurat, resolution = .6)
}else{
  tcell_seurat<- FindClusters(tcell_seurat,  resolution = .7, algorithm = 4, random.seed = 100) ## .6 res used for pedOnly, .7 for pedOnly_nomuv63. Same cluster number
}
FeaturePlot(tcell_seurat, features=c("CD3G", "CD4", "CD8A", "NKG7"), ncol = 2)
ggsave(paste0(figure_dir, "UMAP_Tcell_CD3.4.8.png"), width=6, height=6)

DimPlot(tcell_seurat, label=TRUE)+NoLegend()
VlnPlot(tcell_seurat, features= c("CD3G", "CD4", "CD8A", "NKG7"), ncol=4)
ggsave(paste0(figure_dir, "Vln_Tcell_CD3.4.8.png"), width=12, height=3)


```


## Add final CD4/CD8 annotations
```{r}
## clear cd4/cd8 clusters
cd4_clusters<- c(0,2)
cd8_clusters<- c(1,3) 

tcell_seurat$detailed_annot<- ifelse(tcell_seurat$seurat_clusters %in% cd4_clusters, "CD4",
                                     ifelse(tcell_seurat$seurat_clusters %in% cd8_clusters, "CD8", "issue"))

## Confirm that each cluster expresses CD3 + EITHER CD4 or CD8 (or at least one is clearly higher)
tcell_seurat$cd4.8_cluster<-paste0("cluster", tcell_seurat$seurat_clusters, "_", tcell_seurat$detailed_annot)
DotPlot(tcell_seurat, group.by="cd4.8_cluster", features=c("CD3G", "CD4", "CD8A", "NKG7"))
ggsave(paste0(figure_dir, "CD4.CD8_finalClusterAnnotations_expression.png"), width=5, height=5)
tcell_seurat$cd4.8_cluster<- NULL

## Rerun pipeline on finalized set of cells
tcell_meta<- tcell_seurat@meta.data
if(integration=="HarmonyInt/"){
 tcell_seurat<- RunFullSeurat(tcell_seurat@assays$RNA@counts,RunHarmony = TRUE, samples= tcell_seurat$sampleid) 
}else{
  tcell_seurat<- RunFullSeurat_Immune(tcell_seurat@assays$RNA@counts, tcell_seurat$sampleid)
}
tcell_seurat<- AddMetaData(tcell_seurat, tcell_meta[,!colnames(tcell_meta) %in% colnames(tcell_seurat@meta.data)])


saveRDS(tcell_seurat, file=paste0(analysis_dir, "tcell_seurat.Rds"))
```

## Split Tcell by CD4/CD8, rerun seurat pipeline for each separately
```{r}
cd4_seurat<- subset(tcell_seurat,detailed_annot=="CD4")
cd8_seurat<- subset(tcell_seurat, detailed_annot=="CD8")

cd4_meta<- cd4_seurat@meta.data; cd8_meta<- cd8_seurat@meta.data

if(integration=="HarmonyInt/"){
  cd4_seurat<- RunFullSeurat(cd4_seurat@assays$RNA@counts,RunHarmony = TRUE, samples= cd4_seurat$sampleid)
  cd8_seurat<- RunFullSeurat(cd8_seurat@assays$RNA@counts,RunHarmony = TRUE, samples=  cd8_seurat$sampleid)
}else{
  cd4_seurat<- RunFullSeurat_Immune(cd4_seurat@assays$RNA@counts, cd4_seurat$sampleid)
  cd8_seurat<- RunFullSeurat_Immune(cd8_seurat@assays$RNA@counts, cd8_seurat$sampleid)
}

cd4_seurat<- AddMetaData(cd4_seurat, metadata=cd4_meta[,!colnames(cd4_meta) %in% colnames(cd4_seurat@meta.data)])
cd8_seurat<- AddMetaData(cd8_seurat, metadata=cd8_meta[,!colnames(cd8_meta) %in% colnames(cd8_seurat@meta.data)])

saveRDS(cd4_seurat, file=paste0(analysis_dir, "tcell_cd4_seurat.Rds"))
saveRDS(cd8_seurat, file=paste0(analysis_dir, "tcell_cd8_seurat.Rds"))
```


## Add on CD4/CD8/DC/Bcell annotation to Tcell+Myeloid seurat obj
```{r}
## Add on CD4/CD8
immune_seurat$detailed_annot<- ifelse(colnames(immune_seurat) %in% colnames(cd4_seurat), "CD4", 
                                               ifelse(colnames(immune_seurat) %in% colnames(cd8_seurat), "CD8",
                                                      immune_seurat$broad_annot))
immune_seurat$detailed_annot<- gsub("Tcell", "Tcell_UnclearCD4.CD8", immune_seurat$detailed_annot)

## Add on DC/Bcell
immune_seurat$detailed_annot<- ifelse(colnames(immune_seurat) %in% colnames(myeloid_seurat),
                                      plyr::mapvalues(colnames(immune_seurat), 
                                                      colnames(myeloid_seurat), myeloid_seurat$detailed_annot),
                                      immune_seurat$detailed_annot)


saveRDS(immune_seurat, file=paste0(analysis_dir, "tcell.myeloid_seurat.Rds"))
```

