---
title: "MergeSamples_QC_ToSeurat.Rmd"
author: "Jenna LaBelle"
date: "11/04/21"
output: html_document
---


```{r}
library(Seurat) 

base_dir = "/Users/jlabelle/"
script_dir = "Dropbox (Partners HealthCare)/FilbinLab/data_analysis/Scripts/"
working_dir<- paste0(base_dir, 
                     "Dropbox (Partners HealthCare)/FilbinLab/",
                     "data_analysis/Projects/PD1_Treatment/Immune/")


analysis_dir_tmp<- paste0(working_dir, "/analysis/compare_to_fullCohort/")
figure_dir_tmp<- paste0(working_dir, "/figures/compare_to_fullCohort/")
data_dir_tmp<- paste0(working_dir,"/analysis/detailed_annotation/")

if(!dir.exists(figure_dir_tmp)){dir.create(figure_dir_tmp, recursive = TRUE)}
if(!dir.exists(analysis_dir_tmp)){dir.create(analysis_dir_tmp, recursive = TRUE)}

preprocessing = paste0(base_dir, script_dir, "single_cell_preprocessing_helper_functions.R")
nmf_helper = paste0(base_dir, script_dir, "NMF_helper_function.R")
source(preprocessing)
source(nmf_helper)

```

## Read in processed seurat objects
```{r}
integration<- "HarmonyInt/" ## HarmonyInt/ or ""

analysis_dir<- paste0(analysis_dir_tmp, integration, "/")
figure_dir<- paste0(figure_dir_tmp, integration, "/")
for(x in c(analysis_dir, figure_dir)){if(!dir.exists(x)){dir.create(x)}}
data_dir<- paste0(data_dir_tmp, integration, "/")

tcell_seurat<- readRDS(paste0(data_dir,   "tcell_seurat.Rds"))
cd4_seurat<- readRDS(paste0(data_dir,   "tcell_cd4_seurat.Rds"))
cd8_seurat<- readRDS(paste0(data_dir,   "tcell_cd8_seurat.Rds"))
myeloid_seurat<- readRDS(paste0(data_dir, "myeloid_seurat_noDC.B.Rds"))

```


## Read in marker genes from full cohort
```{r}
cohort<- "pedOnly_nomuv63"

## Myeloid
rank_use<- 6
myeloid_markers<- read.csv(paste0("../../ImmuneIntegration/Preprocessing_byJenna/NMF/Myeloid/analysis/de.novoNMF/",
                                  cohort, "/top_DE_genes_10Xannotated_NMF_rank", rank_use, ".csv"))
myeloid_list<- split(myeloid_markers, f=myeloid_markers$cluster); myeloid_list<- lapply(myeloid_list, function(x){x$gene})

## CD4
rank_use<- 4
cd4_markers<- read.csv(paste0("../../ImmuneIntegration/Preprocessing_byJenna/NMF/CD4/analysis/",
                                  cohort, "/top_DE_genes_annotated_NMF_rank", rank_use, ".csv"))
cd4_list<- split(cd4_markers, f=cd4_markers$cluster); cd4_list<- lapply(cd4_list, function(x){x$gene})

## CD8
rank_use<- 4
cd8_markers<- read.csv(paste0("../../ImmuneIntegration/Preprocessing_byJenna/NMF/CD8/analysis/",
                                  cohort, "/top_DE_genes_annotated_NMF_rank", rank_use, ".csv"))
cd8_list<- split(cd8_markers, f=cd8_markers$cluster); cd8_list<- lapply(cd8_list, function(x){x$gene})
```

## Normalize/center and score myeloid/cd4/cd8 for full cohort markers
```{r}
## Myeloid
cm_list<- NormCenter(myeloid_seurat@assays$RNA@counts)
cm_mean<- rowMeans(log2(cm_list$raw_data + 1))
myeloid_score<- as.data.frame(t(scoreNmfGenes(cm_list$center_data, cm_mean, myeloid_list)))
myeloid_score$MaxProgram<- apply(myeloid_score, 1, function(x){names(x)[which.max(x)]})
myeloid_score$MaxScore<- apply(myeloid_score[,colnames(myeloid_score) != "MaxProgram"], 1, function(x){x[which.max(x)]})

## CD4
cm_list<- NormCenter(cd4_seurat@assays$RNA@counts)
cm_mean<- rowMeans(log2(cm_list$raw_data + 1))
cd4_score<- as.data.frame(t(scoreNmfGenes(cm_list$center_data, cm_mean, cd4_list)))
cd4_score$MaxProgram<- apply(cd4_score, 1, function(x){names(x)[which.max(x)]})
cd4_score$MaxScore<- apply(cd4_score[,colnames(cd4_score) != "MaxProgram"], 1, function(x){x[which.max(x)]})

## CD8
cm_list<- NormCenter(cd8_seurat@assays$RNA@counts)
cm_mean<- rowMeans(log2(cm_list$raw_data + 1))
cd8_score<- as.data.frame(t(scoreNmfGenes(cm_list$center_data, cm_mean, cd8_list)))
cd8_score$MaxProgram<- apply(cd8_score, 1, function(x){names(x)[which.max(x)]})
cd8_score$MaxScore<- apply(cd8_score[,colnames(cd8_score) != "MaxProgram"], 1, function(x){x[which.max(x)]})
```

## Add max programs to seurat, plot
```{r}
## Myeloid
myeloid_seurat$fullCohort_maxProgram<- plyr::mapvalues(colnames(myeloid_seurat), rownames(myeloid_score),
                                                       myeloid_score$MaxProgram)
sum(myeloid_score$MaxScore<0.2) ## 10 cells
colors_use<- c(SEPP1_Mo_TAM ="orange", Inflammatory="red", IFN_TAM="purple", Stress_Response="olivedrab4",
                            Monocytes="turquoise3", Hypoxic_TAM="navy")
DimPlot(myeloid_seurat, group.by = "fullCohort_maxProgram")+scale_color_manual(values=colors_use)
ggsave(paste0(figure_dir, "Myeloid_UMAP_maxFullCohortProgram.png"), width=5, height=4)

## CD4
cd4_seurat$fullCohort_maxProgram<- plyr::mapvalues(colnames(cd4_seurat), rownames(cd4_score),
                                                       cd4_score$MaxProgram)
sum(cd4_score$MaxScore<0.2) ## 33 cells
colors_use<- c(Memory="orange", Inhibitory="red", Effector_Memory="purple", Cytotoxic="olivedrab4")
DimPlot(cd4_seurat, group.by = "fullCohort_maxProgram")+scale_color_manual(values=colors_use)
ggsave(paste0(figure_dir, "CD4_UMAP_maxFullCohortProgram.png"), width=5, height=4)

## CD4
cd8_seurat$fullCohort_maxProgram<- plyr::mapvalues(colnames(cd8_seurat), rownames(cd8_score),
                                                       cd8_score$MaxProgram)
sum(cd8_score$MaxScore<0.2) ## 39 cells
colors_use<- c(Memory="orange", Inhibitory="red", NK="turquoise", Cytotoxic="olivedrab4")
DimPlot(cd8_seurat, group.by = "fullCohort_maxProgram")+scale_color_manual(values=colors_use)
ggsave(paste0(figure_dir, "CD8_UMAP_maxFullCohortProgram.png"), width=5, height=4)
```

## Plot breakdown by sample
```{r}
## Myeloid
colors_use<- c(SEPP1_Mo_TAM ="orange", Inflammatory="red", IFN_TAM="purple", Stress_Response="olivedrab4",
                            Monocytes="turquoise3", Hypoxic_TAM="navy")

  ## Create df for plotting
  myeloid_df<-myeloid_seurat@meta.data[,c("sampleid", "fullCohort_maxProgram")]
  myeloid_bd<- as.data.frame(table(myeloid_df$sampleid, myeloid_df$fullCohort_maxProgram))
  colnames(myeloid_bd)<- c("Sample", "Program", "NCells")
  
  ## Convert n cells to percentage
  myeloid_bd<- myeloid_bd %>% group_by(Sample) %>% mutate(PerCells=NCells/sum(NCells)) %>% as.data.frame()
  
  
  ## Plot
  ggplot(myeloid_bd, aes(x=Sample, y=PerCells, fill=Program))+
    geom_bar(position = "stack", stat="identity")+
    scale_fill_manual(values=colors_use)+
    theme_classic()+
    theme(axis.text.x = element_text(angle=45, hjust=1, color="black", face="bold"),
          axis.text.y = element_text(color="black", face="bold"),
          axis.title.y = element_text(color="black", face="bold"))+
    ylab("Proportion of cells in program")+xlab("")
  ggsave(paste0(figure_dir, "Myeloid_ProgramBreakdownBySample.png"), width=4, height=4)  
  
## CD4
colors_use<- c(Memory="orange", Inhibitory="red", Effector_Memory="purple", Cytotoxic="olivedrab4")

  ## Create df for plotting
  cd4_df<-cd4_seurat@meta.data[,c("sampleid", "fullCohort_maxProgram")]
  cd4_bd<- as.data.frame(table(cd4_df$sampleid, cd4_df$fullCohort_maxProgram))
  colnames(cd4_bd)<- c("Sample", "Program", "NCells")
  
  ## Convert n cells to percentage
  cd4_bd<- cd4_bd %>% group_by(Sample) %>% mutate(PerCells=NCells/sum(NCells)) %>% as.data.frame()
  
  
  ## Plot
  ggplot(cd4_bd, aes(x=Sample, y=PerCells, fill=Program))+
    geom_bar(position = "stack", stat="identity")+
    scale_fill_manual(values=colors_use)+
    theme_classic()+
    theme(axis.text.x = element_text(angle=45, hjust=1, color="black", face="bold"),
          axis.text.y = element_text(color="black", face="bold"),
          axis.title.y = element_text(color="black", face="bold"))+
    ylab("Proportion of cells in program")+xlab("")
  ggsave(paste0(figure_dir, "CD4_ProgramBreakdownBySample.png"), width=4, height=4)  
  
## CD8
colors_use<- c(Memory="orange", Inhibitory="red", NK="turquoise", Cytotoxic="olivedrab4")

  ## Create df for plotting
  cd8_df<-cd8_seurat@meta.data[,c("sampleid", "fullCohort_maxProgram")]
  cd8_bd<- as.data.frame(table(cd8_df$sampleid, cd8_df$fullCohort_maxProgram))
  colnames(cd8_bd)<- c("Sample", "Program", "NCells")
  
  ## Convert n cells to percentage
  cd8_bd<- cd8_bd %>% group_by(Sample) %>% mutate(PerCells=NCells/sum(NCells)) %>% as.data.frame()
  
  
  ## Plot
  ggplot(cd8_bd, aes(x=Sample, y=PerCells, fill=Program))+
    geom_bar(position = "stack", stat="identity")+
    scale_fill_manual(values=colors_use)+
    theme_classic()+
    theme(axis.text.x = element_text(angle=45, hjust=1, color="black", face="bold"),
          axis.text.y = element_text(color="black", face="bold"),
          axis.title.y = element_text(color="black", face="bold"))+
    ylab("Proportion of cells in program")+xlab("")
  ggsave(paste0(figure_dir, "CD8_ProgramBreakdownBySample.png"), width=4, height=4) 

```

## Compare expression of GOI in PD-1 treated vs GBM samples in full immune cohort
```{r}
cohort<- "pedOnly_nomuv63"

## Read in seurat objects for full cohort
full_cd8<- readRDS(paste0("../../ImmuneIntegration/Preprocessing_byJenna/Preprocessing/Counts_Preprocess/analysis/detailed_annotation/",
                            cohort, "/tcell_cd8_seurat.Rds"))
full_cd4<- readRDS(paste0("../../ImmuneIntegration/Preprocessing_byJenna/Preprocessing/Counts_Preprocess/analysis/detailed_annotation/",
                            cohort, "/tcell_cd4_seurat.Rds"))

full_cd8$Cohort<- "FullImmune"; full_cd4$Cohort<- "FullImmune"


## Merge with pd-1 treated
cd8_seurat$Cohort<- "PD1_Treat"
merge_cd8<- merge(full_cd8, cd8_seurat)

cd4_seurat$Cohort<- "PD1_Treat"
merge_cd4<- merge(full_cd4, cd4_seurat)

## Rerun seurat so that scale is the same
merge_cd8_meta<- merge_cd8@meta.data
merge_cd8<- RunFullSeurat_Immune(merge_cd8@assays$RNA@counts, samples=merge_cd8$sampleid)
merge_cd8<- AddMetaData(merge_cd8, metadata=merge_cd8_meta)

merge_cd4_meta<- merge_cd4@meta.data
merge_cd4<- RunFullSeurat_Immune(merge_cd4@assays$RNA@counts, samples=merge_cd4$sampleid)
merge_cd4<- AddMetaData(merge_cd4, metadata=merge_cd4_meta)

## Plot
DotPlot(merge_cd8, features=c("PDCD1", "TIGIT", "KLRB1","CTLA4"), group.by = "sampleid")+
  theme(axis.text.x = element_text(angle=45, hjust=1))+
  ylab("")+xlab("")
ggsave(paste0(figure_dir, "DotPlot_CD8_PD1.fullCohort_inhibitoryGOI.png"), width=5, height=6)

DotPlot(merge_cd4, features=c("PDCD1", "TIGIT", "KLRB1","CTLA4"), group.by = "sampleid")+
  theme(axis.text.x = element_text(angle=45, hjust=1))+
  ylab("")+xlab("")
ggsave(paste0(figure_dir, "DotPlot_CD4_PD1.fullCohort_inhibitoryGOI.png"), width=5, height=6)


```

## Compare proportion of clonal T cells
```{r}
cohort<- "pedOnly_nomuv63"

## Read in seurat objects for full cohort
full_cd8<- readRDS(paste0("../../ImmuneIntegration/Preprocessing_byJenna/Preprocessing/Counts_Preprocess/analysis/detailed_annotation/",
                            cohort, "/tcell_cd8_seurat.Rds"))

full_cd8$Cohort<- "FullImmune"

## Merge with pd-1 treated
cd8_seurat$Cohort<- "PD1_Treat"
merge_cd8<- merge(full_cd8, cd8_seurat)

## Make df of % of clonal cells in each
per_clonal<- as.data.frame(table(merge_cd8$clonal, merge_cd8$sampleid))
colnames(per_clonal)<- c("Clonality", "Sample", "Ncells")
per_clonal<- per_clonal %>% group_by(Sample) %>% mutate(PerCells=Ncells/sum(Ncells)) %>% as.data.frame()
per_clonal<- per_clonal[per_clonal$Clonality=="clonal", ]

## Add on cohort for ordering purpose
per_clonal$Treatment<- plyr::mapvalues(per_clonal$Sample, merge_cd8$sampleid, merge_cd8$Cohort, warn_missing = FALSE)


## Plot
ggplot(per_clonal, aes(x=Sample, y=PerCells))+
  geom_point()+
  theme(axis.text.x = element_text(angle=45, hjust=1))+
  facet_grid(cols=vars(Treatment), scale="free_x", space="free_x")

## Boxplot by Subtype + treatment
per_clonal$Subtype<- as.character(plyr::mapvalues(per_clonal$Sample, merge_cd8$sampleid, merge_cd8$NiceSubtype, warn_missing = FALSE))
per_clonal$Subtype<- ifelse(per_clonal$Treatment=="PD1_Treat", "GBM", per_clonal$Subtype)

ggplot(per_clonal, aes(x=Subtype, y=PerCells))+
  geom_boxplot()+
  geom_point()+
  facet_grid(cols=vars(Treatment), scale="free_x", space="free_x")+
    theme(axis.text.x = element_text(angle=45, hjust=1))+
  ylab("Percentage clonal CD8+ cells")+
  xlab("")
ggsave(paste0(figure_dir, "Boxplot_PropClonalCD8_BySubtype.Cohort.png"), width=5, height=5)
```

