---
title: "ProjectBroadAnnots.Rmd"
author: "Jenna LaBelle"
date: "10/07/22"
output: html_document
---

## Project program annotations from the full immune cohort to tenx sample

```{r}
library(Seurat) 

base_dir = "/Users/jlabelle/"
script_dir = "Dropbox (Partners HealthCare)/FilbinLab/data_analysis/Scripts/"
working_dir<- paste0(base_dir, 
                     "Dropbox (Partners HealthCare)/FilbinLab/",
                     "data_analysis/Projects/git_repos/Pedi_Immune/PD1_Treat/SS2/Tumor/")

analysis_dir<- paste0(working_dir, "/analysis/project_tumor_programs/")
figure_dir<- paste0(working_dir, "/figures/project_tumor_programs/")

if(!dir.exists(figure_dir)){dir.create(figure_dir, recursive = TRUE)}
if(!dir.exists(analysis_dir)){dir.create(analysis_dir, recursive = TRUE)}

preprocessing = paste0(base_dir, script_dir, "single_cell_preprocessing_helper_functions.R")
nmf_helper = paste0(base_dir, script_dir, "NMF_helper_function.R")
source(preprocessing)
source(nmf_helper)
source("../../HelperFunctions.R")
```



## Load seurat objects: pd-1  and full immune cohort 
```{r}
pd1_seurat<- readRDS("analysis/seurat/seurat_obj.Rds")
load("../../../TumorCellAnnotation/AllSubtypesTogether/analysis/Merge_allSubtypes/AllTumorSeuratObj.Robj")
tumor_seurat<- tumor_merged; rm(tumor_merged)
tumor_seurat$CellAnnot<- gsub("cycling", "Cycling", tumor_seurat$CellAnnot)

tumor_colors<-c(Cycling="gold", `Neuronal-like`=)
```

## Subset full cohort to just GBM and rerun clustering
```{r}
## Subset full cohort to GBM and rerun clustering
gbm_seurat<- subset(tumor_seurat, sample %in% c("BT1478", "BT1857","BT1745"))
gbm_meta<- gbm_seurat@meta.data
gbm_seurat<- RunFullSeurat(gbm_seurat@assays$RNA@counts, RunHarmony = TRUE, samples=gbm_meta$sample)
gbm_seurat<- AddMetaData(gbm_seurat, gbm_meta[,!colnames(gbm_meta) %in% colnames(gbm_seurat@meta.data)])

  ## Plot by sample- BT1857 is very different from other 2 GBM (age difference?) throws off projection
  DimPlot(gbm_seurat, group.by = "sample") + DimPlot(gbm_seurat, group.by = "CellAnnot")
  ggsave(paste0(figure_dir, "UMAP_GBM_untreated_WithBT1857_bySample.CellAnnot.png"), width=12, height=5)

## Remove BT1857 and re-run clustering
gbm_seurat<- subset(tumor_seurat, sample %in% c("BT1478","BT1745"))
gbm_meta<- gbm_seurat@meta.data
gbm_seurat<- RunFullSeurat(gbm_seurat@assays$RNA@counts, RunHarmony = TRUE, samples=gbm_meta$sample)
gbm_seurat<- AddMetaData(gbm_seurat, gbm_meta[,!colnames(gbm_meta) %in% colnames(gbm_seurat@meta.data)])

  ## Plot by sample- much better sample integration
  DimPlot(gbm_seurat, group.by = "sample") + DimPlot(gbm_seurat, group.by = "CellAnnot")
  ggsave(paste0(figure_dir, "UMAP_GBM_untreated_WithoutBT1857_bySample.CellAnnot.png"), width=12, height=5)
```


## Projection of cd4 programs to pd1 cd4
```{r}
## Project full to pd1
pd1_seurat<- my_project_seurat(gbm_seurat, pd1_seurat, reference_annotation = "CellAnnot")

## plot
DimPlot(pd1_seurat, group.by="Program_projected", pt.size = 1, label=FALSE, label.size = 6)
  scale_color_manual(values=tcell_colors[names(tcell_colors) %in% pd1_seurat$Program_projected])
ggsave(paste0(figure_dir, "UMAP_CD4_program_projectedFromFull.png"), width=6, height=6)

## Proportion of programs by sample
my_barchart_programProp(pd1_seurat, coloring_variable = "Program_projected", colors=tcell_colors)
ggsave(paste0(figure_dir, "Breakdown_CD4_programBySample.png"), width=4, height=4)

## Expression of expected (same as full cohort) genes in predicted programs
my_dotplot(pd1_seurat, "Program_projected", unique(my_orderFeatures_forDotplot(top_tcell_markers)$gene))
ggsave(paste0(figure_dir, "DotPlot_cd4_topMarkersForFullCohort.png"), width=6, height=8)

## Identify markers for project programs- match expectations?
cd4_markers<- my_get_markers(pd1_seurat, n_top=5, ident="Program_projected")

  ## Confirm expression of expected markers within predicted programs
  my_dotplot(pd1_seurat, "Program_projected", unique(my_orderFeatures_forDotplot(cd4_markers$top_markers)$gene))
  ggsave(paste0(figure_dir, "DotPlot_CD4_topMarkersForReidentifiedPredictedPrograms.png"), width=6, height=8)
  
## Histogram of max program scores for each program
## Helps to determine reasonable "Score too low" threshold
my_histMaxScores(pd1_seurat, "Program_projected", "max_Programscore_projected", tcell_colors)  
ggsave(paste0(figure_dir, "Histogram_CD4_maxProgramScore.png"), width=12, height=9)

## Grey out cells with low confidence score
low_score<- 0.4
pd1_seurat$Program_projected_lowScore<-ifelse(pd1_seurat$max_Programscore_projected<low_score, 
                                           "ScoreTooLow",
                                           pd1_seurat$Program_projected)
DimPlot(pd1_seurat, group.by = "Program_projected_lowScore")+
  scale_color_manual(values=c(tcell_colors[names(tcell_colors) %in% pd1_seurat$Program_projected],
                              ScoreTooLow="grey"))
ggsave(paste0(figure_dir, "UMAP_CD4_maxProgram_scoreTooLow", low_score, ".png"), width=6.5, height=5)

  ## Expression of expected (same as full cohort) genes in predicted programs
  my_dotplot(subset(pd1_seurat, Program_projected_lowScore != "ScoreTooLow"), 
             "Program_projected_lowScore", unique(my_orderFeatures_forDotplot(top_tcell_markers)$gene))
  ggsave(paste0(figure_dir, "DotPlot_CD4_topMarkersForFullCohort_scoreTooLow", low_score, ".png"), width=6, height=8)

  ## Identify markers for project programs- match expectations?
  cd4_markers_lowScore<- my_get_markers(pd1_seurat, n_top=5, ident="Program_projected_lowScore", excludeProgram = "ScoreTooLow")
  
  ## Confirm expression of expected markers within predicted programs
  my_dotplot(pd1_seurat, "Program_projected_lowScore", unique(my_orderFeatures_forDotplot(cd4_markers_lowScore$top_markers)$gene))
  ggsave(paste0(figure_dir, "DotPlot_CD4_topMarkersForReidentifiedPredictedPrograms_scoreTooLow", low_score, ".png"), width=6, height=8)

saveRDS(pd1_seurat, file=paste0(pd1_data_dir, "pd1_seurat_seurat.Rds"))
```

## Projection of cd8 programs to pd1 cd8
```{r}
pd1_cd8<- my_project_seurat(full_cd8_seurat, pd1_cd8, reference_annotation = "NMF_rank8_annot_mergedByunion_reAnnot")

## plot
DimPlot(pd1_cd8, group.by="Program_projected", pt.size = 1, label=FALSE, label.size = 6)+ 
  scale_color_manual(values=tcell_colors[names(tcell_colors) %in% pd1_cd8$Program_projected])
ggsave(paste0(figure_dir, "UMAP_CD8_program_projectedFromFull.png"), width=6, height=6)

## Proportion of programs by sample
my_barchart_programProp(pd1_cd8, coloring_variable = "Program_projected", colors=tcell_colors)
ggsave(paste0(figure_dir, "Breakdown_cd8_programBySample.png"), width=4, height=4)

## Expression of expected (same as full cohort) genes in predicted programs
my_dotplot(pd1_cd8, "Program_projected", unique(my_orderFeatures_forDotplot(top_tcell_markers)$gene))
ggsave(paste0(figure_dir, "DotPlot_cd8_topMarkersForFullCohort.png"), width=6, height=8)

## Identify markers for project programs- match expectations?
cd8_markers<- my_get_markers(pd1_cd8, n_top=5, ident="Program_projected")

  ## Expression of top markers for each predicted program
  my_dotplot(pd1_cd8, "Program_projected", unique(my_orderFeatures_forDotplot(cd8_markers$top_markers)$gene))
  ggsave(paste0(figure_dir, "DotPlot_cd8_topMarkersForReidentifiedPredictedPrograms.png"), width=6, height=8)

  
## Histogram of max program scores for each program
## Helps to determine reasonable "Score too low" threshold
my_histMaxScores(pd1_cd8, "Program_projected", "max_Programscore_projected", tcell_colors)  
ggsave(paste0(figure_dir, "Histogram_CD8_maxProgramScore.png"), width=12, height=9)

## Grey out cells with low confidence score
low_score<- 0.4
pd1_cd8$Program_projected_lowScore<-ifelse(pd1_cd8$max_Programscore_projected<low_score, 
                                           "ScoreTooLow",
                                           pd1_cd8$Program_projected)
DimPlot(pd1_cd8, group.by = "Program_projected_lowScore")+
  scale_color_manual(values=c(tcell_colors[names(tcell_colors) %in% pd1_cd8$Program_projected],
                              ScoreTooLow="grey"))
ggsave(paste0(figure_dir, "UMAP_CD8_maxProgram_scoreTooLow", low_score, ".png"), width=6.5, height=5)

  ## Expression of expected (same as full cohort) genes in predicted programs
  my_dotplot(subset(pd1_cd8, Program_projected_lowScore != "ScoreTooLow"), 
             "Program_projected_lowScore", unique(my_orderFeatures_forDotplot(top_tcell_markers)$gene))
  ggsave(paste0(figure_dir, "DotPlot_cd8_topMarkersForFullCohort_scoreTooLow", low_score, ".png"), width=6, height=8)

  ## Identify markers for project programs- match expectations?
  cd8_markers_lowScore<- my_get_markers(pd1_cd8, n_top=5, ident="Program_projected_lowScore", excludeProgram = "ScoreTooLow")
  
  ## Confirm expression of expected markers within predicted programs
  my_dotplot(pd1_cd8, "Program_projected_lowScore", unique(my_orderFeatures_forDotplot(cd8_markers_lowScore$top_markers)$gene))
  ggsave(paste0(figure_dir, "DotPlot_cd8_topMarkersForReidentifiedPredictedPrograms_scoreTooLow", low_score, ".png"), width=6, height=8)

saveRDS(pd1_cd8, file=paste0(pd1_data_dir, "pd1_cd8_seurat.Rds"))
```

## Projection of myeloid programs to pd1 myeloid
```{r}
pd1_myeloid<- my_project_seurat(full_myeloid_seurat, pd1_myeloid, reference_annotation = "NMF_rank6_annotByAdult10X")

## plot
DimPlot(pd1_myeloid, group.by="Program_projected", pt.size = 1, label=FALSE, label.size = 6)+ 
  scale_color_manual(values=myeloid_colors[names(myeloid_colors) %in% pd1_myeloid$Program_projected])
ggsave(paste0(figure_dir, "UMAP_myeloid_program_projectedFromFull.png"), width=6, height=6)

## Proportion of programs by sample
my_barchart_programProp(pd1_myeloid, coloring_variable = "Program_projected", colors=myeloid_colors)
ggsave(paste0(figure_dir, "Breakdown_myeloid_programBySample.png"), width=4, height=4)

## Expression of expected (same as full cohort) genes in predicted programs
my_dotplot(pd1_myeloid, "Program_projected", unique(my_orderFeatures_forDotplot(top_myeloid_markers)$gene))
ggsave(paste0(figure_dir, "DotPlot_myeloid_topMarkersForFullCohort.png"), width=6, height=8)

## Identify markers for project programs- match expectations?
myeloid_markers<- my_get_markers(pd1_myeloid, n_top=5, ident="Program_projected")

  ## Expression of top markers for each predicted program
  my_dotplot(pd1_myeloid, "Program_projected", unique(my_orderFeatures_forDotplot(myeloid_markers$top_markers)$gene))
  ggsave(paste0(figure_dir, "DotPlot_myeloid_topMarkersForReidentifiedPredictedPrograms.png"), width=6, height=8)

  
## Histogram of max program scores for each program
## Helps to determine reasonable "Score too low" threshold
my_histMaxScores(pd1_myeloid, "Program_projected", "max_Programscore_projected", myeloid_colors)  
ggsave(paste0(figure_dir, "Histogram_myeloid_maxProgramScore.png"), width=12, height=9)

## Grey out cells with low confidence score
low_score<- 0.4
pd1_myeloid$Program_projected_lowScore<-ifelse(pd1_myeloid$max_Programscore_projected<low_score, 
                                           "ScoreTooLow",
                                           pd1_myeloid$Program_projected)
DimPlot(pd1_myeloid, group.by = "Program_projected_lowScore")+
  scale_color_manual(values=c(myeloid_colors[names(myeloid_colors) %in% pd1_myeloid$Program_projected],
                              ScoreTooLow="grey"))
ggsave(paste0(figure_dir, "UMAP_myeloid_maxProgram_scoreTooLow", low_score, ".png"), width=6.5, height=5)

  ## Expression of expected (same as full cohort) genes in predicted programs
  my_dotplot(subset(pd1_myeloid, Program_projected_lowScore != "ScoreTooLow"), 
             "Program_projected_lowScore", unique(my_orderFeatures_forDotplot(top_myeloid_markers)$gene))
  ggsave(paste0(figure_dir, "DotPlot_myeloid_topMarkersForFullCohort_scoreTooLow", low_score, ".png"), width=6, height=8)

  ## Identify markers for project programs- match expectations?
  myeloid_markers_lowScore<- my_get_markers(pd1_myeloid, n_top=5, ident="Program_projected_lowScore", excludeProgram = "ScoreTooLow")
  
  ## Confirm expression of expected markers within predicted programs
  my_dotplot(pd1_myeloid, "Program_projected_lowScore", unique(my_orderFeatures_forDotplot(myeloid_markers_lowScore$top_markers)$gene))
  ggsave(paste0(figure_dir, "DotPlot_myeloid_topMarkersForReidentifiedPredictedPrograms_scoreTooLow", low_score, ".png"), width=6, height=8)

saveRDS(pd1_myeloid, file=paste0(pd1_data_dir, "myeloid_pd1_noDC.B_seurat.Rds"))
```


