---
title: "ProjectBroadAnnots.Rmd"
author: "Jenna LaBelle"
date: "10/07/22"
output: html_document
---

## Project program annotations from the full immune cohort to tenx sample

```{r}
library(Seurat) 
library(ggalluvial)

base_dir = "/Users/jlabelle/"
script_dir = "Dropbox (Partners HealthCare)/FilbinLab/data_analysis/Shared/Scripts/"
working_dir<- paste0(base_dir, 
                     "Dropbox (Partners HealthCare)/FilbinLab/",
                     "data_analysis/Projects/git_repos/Pedi_Immune/PD1_Treat/01b_tenX/")

analysis_dir<- paste0(working_dir, "/analysis/project_programs/")
figure_dir<- paste0(working_dir, "/figures/project_programs/")
data_dir<- paste0(working_dir, "analysis/Merge/")
full_cohort_dir<- "../../ImmuneCellAnalysis/"

if(!dir.exists(figure_dir)){dir.create(figure_dir, recursive = TRUE)}
if(!dir.exists(analysis_dir)){dir.create(analysis_dir, recursive = TRUE)}

preprocessing = paste0(base_dir, script_dir, "single_cell_preprocessing_helper_functions.R")
nmf_helper = paste0(base_dir, script_dir, "NMF_helper_function.R")
source(preprocessing)
source(nmf_helper)
source(paste0(base_dir, script_dir, "seurat_transferAnchors_helper.R"))

```


## Load seurat objects: pd-1 (processed in 01b_PreprocetenxQC_ToSeurat.Rmd) and full immune cohort (both myeloid and t cells)

```{r}
## Load merged tenx (pd1, untreated)
tenx_files<- list.files(data_dir, pattern="seurat")
tenx_files<- tenx_files[!grepl("tcell", tenx_files)]


tenx_seurat<- lapply(tenx_files, function(x){readRDS(paste0(data_dir, x))})
names(tenx_seurat)<-  gsub("_seurat.Rds", "", tenx_files)
tenx_seurat<- lapply(tenx_seurat, function(x){x$Sequencing<- "tenx"; return(x)})



## Full cohort seurat objects (ss2 for projection)
full_myeloid_seurat<- readRDS(paste0(full_cohort_dir,
                                     "01_Preprocessing/02_Counts_Preprocess/analysis/detailed_annotation/",
                                     "pedOnly_nomuv63/",
                                     "myeloid_seurat_noDC.B_harmony.Rds"))
full_myeloid_seurat$Final_Annot<-full_myeloid_seurat$NMF_rank6_annotByAdult10X
full_cd4_seurat<- readRDS(paste0(full_cohort_dir,
                                   "02a_Tcells/02_Ped.Adult/03_Visualize.Reannotate_programs/analysis/Reannotate_programs/",
                                   "rank8_sharedByunion/",
                                   "ped_seurat_cd4_harmony.Rds"))
full_cd8_seurat<- readRDS(paste0(full_cohort_dir,
                                   "02a_Tcells/02_Ped.Adult/03_Visualize.Reannotate_programs/analysis/Reannotate_programs/",
                                   "rank8_sharedByunion/",
                                   "ped_seurat_cd8_harmony.Rds"))

## Colors 
tcell_colors<- readRDS(paste0(full_cohort_dir, "/plot_colors/Tcell.programs_rank8sharedByunion_reAnnot.Rds"))
tcell_colors<- c(tcell_colors, Activated_EM="red")
myeloid_colors<- readRDS(paste0(full_cohort_dir, "/plot_colors/Myeloid_program_colors.Rds"))
myeloid_colors<- myeloid_colors$rank6
myeloid_colors<- c(myeloid_colors, CD3pos_Myeloid="green", Microglia="olivedrab4")
immune_colors<- c(tcell_colors, myeloid_colors)
colors_treatment<- c(PD1="orange", Untreated="purple")

## untreated cohort marker genes
tcell_markers<- readRDS(paste0(full_cohort_dir, 
                             "02a_Tcells/02_Ped.Adult/01_compare_NMF/analysis/newMarkers_deNovoPed.AdultTcell/", 
                             "new_markers_NMFrank8_bySeurat_sharedByunion_reAnnot.Rds"))
myeloid_markers<- read.csv(paste0(full_cohort_dir,
                               "02b_Myeloid/01a_NMF/analysis/de.novoNMF/pedOnly_nomuv63/", 
                               "top_DE_genes_10Xannotated_NMF_rank6.csv"))


  ## Top markers per program
  top_tcell_markers<- tcell_markers %>% group_by(cluster) %>% top_n(n=5, wt=avg_log2FC) %>% as.data.frame()
  top_myeloid_markers<- myeloid_markers %>% group_by(cluster) %>% top_n(n=5, wt=avg_log2FC) %>% as.data.frame()

```




## Project programs from full cohort to 10x
```{r}
## Project
tenx_seurat$cd4<- my_project_seurat(full_cd4_seurat,tenx_seurat$cd4, reference_annotation = "NMF_rank8_annot_mergedByunion_reAnnot")
tenx_seurat$cd8<- my_project_seurat(full_cd8_seurat,tenx_seurat$cd8, reference_annotation = "NMF_rank8_annot_mergedByunion_reAnnot")
tenx_seurat$myeloid<- my_project_seurat(full_myeloid_seurat,tenx_seurat$myeloid, reference_annotation = "NMF_rank6_annotByAdult10X")


for(i in names(tenx_seurat)){
  saveRDS(tenx_seurat[[i]], file=paste0(data_dir, i, "_seurat.Rds"))
}

```





## UMAPs of projected programs
```{r}
## Load files
files<- list.files(data_dir)
tenx_seurat<- lapply(files, function(x){readRDS(paste0(data_dir, x))})
names(tenx_seurat)<- gsub("_seurat.Rds", "", files)

all_plots<- lapply(names(tenx_seurat), function(x){
  tmp<- tenx_seurat[[x]]
  DimPlot(tmp, group.by="Program_projected", pt.size = 1, label=FALSE, label.size = 6)+ 
    scale_color_manual(values=immune_colors[names(immune_colors) %in% tmp$Program_projected])+
    ggtitle(x)
})
cowplot::plot_grid(plotlist=all_plots, ncol=3)
ggsave(paste0(figure_dir, "tenx_UMAP_PredictedProgram.png"), width=18, height=5)

```

## Barchart of program proportions
```{r}

all_plots<- lapply(names(tenx_seurat), function(x){
  tmp<- tenx_seurat[[x]]
  my_barchart_programProp(tmp, coloring_variable = "Program_projected", colors=immune_colors)+ggtitle(x)
})
cowplot::plot_grid(plotlist=all_plots, ncol=3)
ggsave(paste0(figure_dir, "tenx_Barchart_PredictedProgram.png"), width=18, height=5)

```

## Pseudobulked heatmap of expression of marker genes
```{r}
marker_list<- list(cd4=top_tcell_markers[!top_tcell_markers$cluster %in% c("Predysfunctional", "Cytotoxic.NKreceptor"),], 
                   cd8=top_tcell_markers[!top_tcell_markers$cluster %in% c("Treg", "Inhibitory"),], 
                   myeloid=top_myeloid_markers)

samples<-c("BT1857", "BT2062", "BT2080") 
all_plots<- lapply(names(tenx_seurat), function(x){
  tmp<- tenx_seurat[[x]]
  markers_use<-marker_list[[x]]
  markers_use<- markers_use[markers_use$cluster %in% unique(tmp$Program_projected),]
  markers_use<- markers_use[markers_use$gene %in% rownames(tmp),]
  
  samples_use<-samples[samples %in% unique(tmp$sample)]
  
  ## Create pseudobulking variable
  tmp$pb<- paste0(tmp$sample, "_", gsub("\\.", "\n", gsub("_", "\n", tmp$Program_projected)))
  pb<- pseudobulk_byVariable(tmp, tmp@meta.data, "pb")
  
  
  ## center for each sample separately
  center_bySample<- lapply(unique(tmp$sample), function(sample){
    pb_tmp<- pb[,grepl(sample, colnames(pb))]
    if(class(pb_tmp)=="numeric"){
      pb_tmp<- as.data.frame(pb_tmp)
      colnames(pb_tmp)<- colnames(pb)[grepl(sample, colnames(pb))]
    }
    pb_list_tmp<- NormCenter(pb_tmp)
    pb_center_tmp<- pb_list_tmp$center_data
    return(pb_center_tmp)
  })
  center_bySample<- do.call("cbind", center_bySample)

  
  ## Plot
  myHeatmap(center_bySample, GOI=markers_use$gene, min.value = -3, max.value = 3, 
                orderFactors =  gsub("\\.", "\n",gsub("_", "\n", unique(markers_use$cluster))),
            orderSubtypes =samples_use) +
    scale_fill_gradient2(high="red", low="blue", mid="white", name="Centered log2(TPM)")+
    ggtitle(x)
})
cowplot::plot_grid(plotlist=all_plots, ncol=3)
ggsave(paste0(figure_dir, "Heatmap_ExpectedMarkerGenes_All.png"), width=35, height=9)
```

