---
title: "ProjectBroadAnnots.Rmd"
author: "Jenna LaBelle"
date: "10/07/22"
output: html_document
---

## Project program annotations from the full immune cohort to PD1 treated patients

```{r}
library(Seurat) 

base_dir = "/Users/jlabelle/"
script_dir = "Dropbox (Partners HealthCare)/FilbinLab/data_analysis/Scripts/"
working_dir<- paste0(base_dir, 
                     "Dropbox (Partners HealthCare)/FilbinLab/",
                     "data_analysis/Projects/git_repos/Pedi_Immune/PD1_Treat/tenX/")

analysis_dir<- paste0(working_dir, "/analysis/plot_GOI/")
figure_dir<- paste0(working_dir, "/figures/plot_GOI/")

if(!dir.exists(figure_dir)){dir.create(figure_dir, recursive = TRUE)}
if(!dir.exists(analysis_dir)){dir.create(analysis_dir, recursive = TRUE)}

preprocessing = paste0(base_dir, script_dir, "single_cell_preprocessing_helper_functions.R")
nmf_helper = paste0(base_dir, script_dir, "NMF_helper_function.R")
source(preprocessing)
source(nmf_helper)

```

## Load seurat objects: pd-1 
```{r}
pd1_data_dir<- paste0(working_dir, "/analysis/project_broad.detailed_annot/")

#pd1_myeloid<- readRDS(paste0(pd1_data_dir, "myeloid_pd1_noDC.B_seurat.Rds"))
pd1_cd4<- readRDS(paste0(pd1_data_dir, "cd4_pd1_seurat.Rds"))
pd1_cd8<- readRDS(paste0(pd1_data_dir, "cd8_pd1_seurat.Rds"))


## Colors 
tcell_colors<- readRDS(paste0(full_cohort_dir, "/plot_colors/Tcell.programs_rank8sharedByunion_reAnnot.Rds"))
myeloid_colors<- readRDS(paste0(full_cohort_dir, "/plot_colors/Myeloid_program_colors.Rds"))
myeloid_colors<- myeloid_colors$rank6
```


## Feature plot
```{r}
## CD8
cowplot::plot_grid(plotlist=lapply(c("KLRB1", "PTGER2", "SELPLG"), function(x){
  FeaturePlot(cd8_seurat, features=x)+
    scale_color_gradient(low="grey", high="red")
}), ncol=3)
ggsave(paste0(figure_dir, "CD8_UMAP_InhibitoryGenes.png"), width=10, height=3)
```

## Dotplot by program
```{r}
DotPlot(pd1_cd8, features=c("KLRB1", "PTGER2", "SELPLG"), group.by = "Program_projected")+
  scale_color_gradient2(low="blue", mid="white", high = "red")+
  theme(axis.text.x = element_text(angle=45, hjust=1))
ggsave(paste0(figure_dir, "CD8_DotPlot_InhibitoryGenes_byProgram.png"), width=6, height=4)
```

