---
title: ""
author: "Jenna LaBelle"
date: "10/07/22"
output: html_document
---

## Project "broad" (T cell and myeloid) and "detailed" (CD4, CD8, DC, Monocyte, Bcell) annotations from the full immune cohort to tenx patients

```{r}
library(Seurat) 

base_dir = "/Users/jlabelle/"
script_dir = "Dropbox (Partners HealthCare)/FilbinLab/data_analysis/Scripts/"
working_dir<- paste0(base_dir, 
                     "Dropbox (Partners HealthCare)/FilbinLab/",
                     "data_analysis/Projects/git_repos/Pedi_Immune/ImmuneCellAnalysis/tenX/withPD1TreatedTenX/")

analysis_dir<- paste0(working_dir, "/analysis/merge/")
figure_dir<- paste0(working_dir, "/figures/merge/")

if(!dir.exists(figure_dir)){dir.create(figure_dir, recursive = TRUE)}
if(!dir.exists(analysis_dir)){dir.create(analysis_dir, recursive = TRUE)}

preprocessing = paste0(base_dir, script_dir, "single_cell_preprocessing_helper_functions.R")
nmf_helper = paste0(base_dir, script_dir, "NMF_helper_function.R")
source(preprocessing)
source(nmf_helper)

```



## Load seurat objects: tenx (processed in 01_Preprocessing.Rmd) and PD1 tenX (Pedi_Immune/PD1_Treat/tenX/01_Preprocessing.Rmd)
```{r}
untreated_seurat<- readRDS("../unTreatedAlone/analysis/Preprocessing/immune_seurat_obj.Rds")
treated_seurat<- readRDS("../../../PD1_Treat/tenX/analysis/preprocessing/seurat_obj_noAC.Unknown.Rds")

treat_colors<- c(treated="purple", untreated="orange")
```

## Merge and recluster
```{r}
## Fix any metadata column names to match between treated/untreated
untreated_seurat$percent_mito<- untreated_seurat$perMito
treated_seurat$sampleID<- treated_seurat$sample
untreated_seurat$sampleID<- untreated_seurat$sample

## Add on treatment
untreated_seurat$treatment<- "untreated"
treated_seurat$treatment<- "treated"

## Subset to shared metadata
untreated_seurat@meta.data<- untreated_seurat@meta.data[,colnames(untreated_seurat@meta.data) %in% colnames(treated_seurat@meta.data)]
treated_seurat@meta.data<- treated_seurat@meta.data[,colnames(treated_seurat@meta.data) %in% colnames(untreated_seurat@meta.data)]

## Merge into single object
merged_seurat<- merge(untreated_seurat, treated_seurat)
merged_meta<- merged_seurat@meta.data

## Rerun clustering- without integration
merged_seurat<- RunFullSeurat(merged_seurat@assays$RNA@counts, RunHarmony = FALSE, samples=merged_meta$treatment)
merged_seurat<- AddMetaData(merged_seurat, merged_meta[,!colnames(merged_meta) %in% colnames(merged_seurat@meta.data)])

## Rerun clustering- with integration
merged_seurat_harmony<- RunFullSeurat(merged_seurat@assays$RNA@counts, RunHarmony = TRUE, samples=merged_meta$treatment)
merged_seurat_harmony<- AddMetaData(merged_seurat_harmony, merged_meta[,!colnames(merged_meta) %in% colnames(merged_seurat_harmony@meta.data)])

## Save
saveRDS(merged_seurat, file=paste0(analysis_dir, "treated_untreated_merged_noIntegration_seurat.Rds"))
saveRDS(merged_seurat_harmony, file=paste0(analysis_dir, "treated_untreated_merged_harmony_seurat.Rds"))
```

## Exploratory plots to show integration, etc
```{r}
unintegrated_seurat<- readRDS(paste0(analysis_dir, "treated_untreated_merged_noIntegration_seurat.Rds"))
integrated_seurat<- readRDS(paste0(analysis_dir, "treated_untreated_merged_harmony_seurat.Rds"))



## By treatment
DimPlot(unintegrated_seurat, group.by = "treatment") + 
  scale_color_manual(values=treat_colors)
ggsave(paste0(figure_dir, "UMAP_unintegrated_byTreatment.png"), width=6, height=5)

DimPlot(integrated_seurat, group.by = "treatment") + 
  scale_color_manual(values=treat_colors)
ggsave(paste0(figure_dir, "UMAP_integrated_byTreatment.png"), width=6, height=5)

## Quick marker expression
FeaturePlot(unintegrated_seurat, features=c("CSF1R", "CD3G", "CD8A", "CD4"))
ggsave(paste0(figure_dir, "UMAP_unintegrated_byBroadAnnotMarkers.png"), width=7, height=6)

FeaturePlot(integrated_seurat, features=c("CSF1R", "CD3G", "CD8A", "CD4"))
ggsave(paste0(figure_dir, "UMAP_ integrated_byBroadAnnotMarkers.png"), width=7, height=6)
```

